Feature/um metrics 01
SoftwareAG/webmethods-application-collaboration-examples pull request #1
Opened 2023-11-20 14:18 UTC by fivsag

2023-11-24 07:24 UTC, miunsag requested changes
Please produce a README file in the same folder as the docker-compose.yml file. Each project will have their own README.
Second, I have mapped a valid license file but it went in error. It seems it wants to mount a folder (?)

in .env:
UM_LICENCE_LOCATION=c:\v\Lic\exp_2024-11-30\wm10x-current\Linux\Universal Messaging Integr AP\0000763146_UniversalMessaging_Integration105.xml

error:
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/mnt/c/v/Lic/exp_2024-11-30/wm10x-current/Linux/Universal Messaging Integr AP/0000763146_UniversalMessaging_Integration105.xml" to rootfs at "/opt/softwareag/UniversalMessaging/server/umserver/licence": mount /mnt/c/v/Lic/exp_2024-11-30/wm10x-current/Linux/Universal Messaging Integr AP/0000763146_UniversalMessaging_Integration105.xml:/opt/softwareag/UniversalMessaging/server/umserver/licence (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

2023-11-24 07:41 UTC, fivsag commented
- README file moved
- Please use a relative path to the local folder that contains the valid UM license file. eg:
![image](https://github.com/SoftwareAG/webmethods-application-collaboration-examples/assets/105639055/4c8d5581-6eca-45c7-8ed4-f518d27457ba)

2023-11-24 07:42 UTC, miunsag requested changes
Please observe the comments and suggestions

2023-11-24 07:42 UTC, miunsag commented on compose/um-metrics-02/docker-compose.yml
> +     - 9200:9200
```suggestion
      - 9000:9000
      - 9200:9200
```

2023-11-24 07:42 UTC, miunsag commented on compose/um-metrics-02/docker-compose.yml
> +     - 9200:9200
Indentation is missing a space?

2023-11-24 07:42 UTC, miunsag commented on compose/um-metrics-02/docker-compose.yml
> +     - um_users:/opt/softwareag/common/conf
```suggestion
      - um_data:/opt/softwareag/UniversalMessaging/server/umserver/data
      - um_logs:/opt/softwareag/UniversalMessaging/server/umserver/logs
      - ${UM_LICENCE_LOCATION}:/opt/softwareag/UniversalMessaging/server/umserver/licence
      - um_users:/opt/softwareag/common/conf
```

2023-11-24 07:42 UTC, miunsag commented on compose/um-metrics-02/docker-compose.yml
> +     - um_users:/opt/softwareag/common/conf
Indentation is missing a space?

2023-11-24 07:42 UTC, miunsag commented on compose/um-metrics-02/helpers/cleaner.sh
> +# echo 'Revoming docker container volumes (if any)'
```suggestion
# echo 'Removing docker container volumes (if any)'
```

2023-11-24 07:42 UTC, miunsag commented on compose/um-metrics-02/docker-compose.yml
> +     - ${UM_LICENCE_LOCATION}:/opt/softwareag/UniversalMessaging/server/umserver/licence
```suggestion
     - ${UM_LICENCE_LOCATION}:/opt/softwareag/UniversalMessaging/server/umserver/licence/
```

2023-11-24 07:42 UTC, miunsag commented on compose/um-metrics-02/docker-compose.yml
> +     - ${UM_LICENCE_LOCATION}:/opt/softwareag/UniversalMessaging/server/umserver/licence
Add a slash to quickly tell the yaml reader this is a directory mount, not a file mount.
Besides, add a note in the README that the directory needs to contain a file called exactly "licence.xml"

2023-11-24 07:42 UTC, miunsag commented on compose/um-metrics-02/docker-compose.yml
> +      - 9090:9090
```suggestion
      - ${H_SUIF_PORT_PREFIX}90:9090
```

2023-11-24 07:42 UTC, miunsag commented on compose/um-metrics-02/docker-compose.yml
> +     - 9000:9000
```suggestion
     - ${H_SUIF_PORT_PREFIX}900:9000
```

2023-11-24 07:42 UTC, miunsag commented on compose/um-metrics-02/docker-compose.yml
> +     - 9200:9200
```suggestion
     - ${H_SUIF_PORT_PREFIX}920:9200
```

2023-11-24 07:42 UTC, miunsag commented on compose/um-metrics-02/docker-compose.yml
> +      - 9090:9090
```suggestion
      - ${H_SUIF_PORT_PREFIX}90:9090
```

2023-11-24 07:42 UTC, miunsag commented on compose/um-metrics-02/docker-compose.yml
> +      - 9100:9100
```suggestion
      - ${H_SUIF_PORT_PREFIX}00:9100
```

2023-11-24 07:42 UTC, miunsag commented on compose/um-metrics-02/docker-compose.yml
> +      - 9100:9100
Actually the besides the Grafana port, and maybe UM, any other port may be not mapped at all...

2023-11-29 13:37 UTC, miunsag approved these changes

2023-11-29 13:38 UTC, merged